### ISSUE TITLE
Any reason for not open-sourcing the plugin?

### ISSUE THREAD

**Issue by sroze** [lunisolar/LNKD.tech-Editor#14]
Hi @lunisolar. Any particular reason for not open-sourcing this InteliJ plugin which would be very helpful for the Linked Data community?

**Comment by lunisolar** [comment]
One of the main reasons (if not the reason) for open-source is collaboration. 
At this stage of the project I want to be able to do things more freely (including by two custom libraries I use - perpetually in snapshot version). 

One thing I want to keep is for the plugin to be free. Do you see here some obstacles in that regard for the plugin? (e.g. license or otherwise, maybe open-source project than cannot utilize plugin).
