### ISSUE TITLE
Unresolved namespace reference: http://purl.org/linked-data/cube# for purl namespaces

### ISSUE THREAD

**Issue by OscarVanL** [lunisolar/LNKD.tech-Editor#5]
Hi, I'm having problems using certain purl namespaces with your plugin, such as [The RDF Data Cube Vocabulary](https://www.w3.org/TR/vocab-data-cube/) or scovo.

![image](https://user-images.githubusercontent.com/7999692/109507528-c09b0500-7a96-11eb-9810-bc555a1c532f.png)

The above error is shown when viewing the data cube [example](http://purl.org/linked-data/cube).

Any ideas why this is happening, and how I can add purl namespaces to the plugin?

Thanks!

**Comment by lunisolar** [comment]
In general current version of the plugin does not download graphs. It has only some most common built-in as "Global graphs". When you go to the IDE settings you can find plugin's settings. It is either under "Other settings/LNKD.tech Editor" or directly "LNKD.tech Editor" (depends if there is another plugin with "other" settings). 

Global graphs is the section of the settings that should interest you. It is divided into "Builtin Graphs" and "Custom Graphs". You can disable the built-in and add any graph you want from local disk into the custom category. This way the graphs will be recognized by the plugin and at the same are not part of the project (not commit-able to GIT). 

I do not invest into the functionality of downloading the graphs (yet), because I do not think there is a wide standard for this.  Except for naive request for the URL hopping that graph will be dereference-able in TTL format, but I expect very low ratio of responses that actually will return TTL instead of HTML page (regardless of content negotiation in HTTP)
Or do you have different opinion?

**Comment by OscarVanL** [comment]
I see. Thanks for the explanation. Frankly, I am new to this so do not know where the limits of TTL/RTF graph schemas lie.
